<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.t10wrab' shared service.

return $this->services['service_locator.t10wrab'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('mailer' => function () {
    $f = function (\AppBundle\Service\Mailer $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Service\Mailer']) ? $this->services['AppBundle\Service\Mailer'] : $this->load('getMailerService.php')) && false ?: '_'});
}));
