<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container78ql6or\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container78ql6or/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container78ql6or.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container78ql6or\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container78ql6or\appDevDebugProjectContainer(array(
    'container.build_hash' => '78ql6or',
    'container.build_id' => '30b8b122',
    'container.build_time' => 1525684876,
), __DIR__.\DIRECTORY_SEPARATOR.'Container78ql6or');
