<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFkha4lh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFkha4lh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFkha4lh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFkha4lh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFkha4lh\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fkha4lh',
    'container.build_id' => 'f17f8cb8',
    'container.build_time' => 1527778768,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFkha4lh');
