<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRqrmwdr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRqrmwdr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRqrmwdr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRqrmwdr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRqrmwdr\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rqrmwdr',
    'container.build_id' => 'b4a3d040',
    'container.build_time' => 1526471191,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRqrmwdr');
